### ISSUE TITLE
Enable running CI with auto_explain enabled.

### ISSUE THREAD

**Issue by emelsimsek** [citusdata/test-automation#259]
In order to make sure Citus works fine with auto_explain, let's enable running CI with auto_explain enabled. Here is an example configuration:

  postgresql.conf
      shared_preload_libraries = 'citus,pg_stat_statements,auto_explain'
      auto_explain.log_min_duration = 0
      auto_explain.log_analyze = true
      auto_explain.log_buffers = true
      auto_explain.log_nested_statements = true

auto_explain  comes built-in with  postgresql. No need for additional install.

As an important note, those new tests in CI, as they are likely to fail, should not block github merge workflow for PRs at the moment.

**Comment by aykut-bozkurt** [comment]
After discussion with @emelsimsek, we decided to support that at [citus repo](https://github.com/citusdata/citus) for now.
But we also have a plan to run citus tests with any other extensions created with the help of extension tests automation.
You can follow the issue # to be aware of the task status.
