### ISSUE TITLE
Setup tasks performs unnecessarily build postgres

### ISSUE THREAD

**Issue by mtuncer** [citusdata/test-automation#55]
I always found myself building postgres when issue any setup.xxx tasks. We should not be building postgres when not needed

**Comment by lithp** [comment]
I could have sworn I already had a ticket for this... Before we can reuse the existing install we need to check:

- pg_config exists
- the `VERSION` line matches the version we want to install
- the `CONFIGURE` line matches the flags we want to use

If all these are true the `setup_postgres` task can return early.
