### ISSUE TITLE
Tab Completion for Fabric Tasks

### ISSUE THREAD

**Issue by lithp** [citusdata/test-automation#6]

**Comment by onderkalaci** [comment]
I found a repo on github which does it in a very simple way: [bash-autocomplete](https://github.com/marcelor/fabric-bash-autocompletion). I tried this manually, and this worked great.

I think could make the `fab` experience much better.

**Comment by lithp** [comment]
[Just pushed](https://github.com/citusdata/test-automation/commit/e214d8ae04f3ed4111df4d7ad4bdfb594bbdd59f) support for this.
